mozilla/mig

Makefile
doc/Makefile
doc/cheatsheet.rst
doc/cheatsheet.rst.html

Notes:
- I think rst2html is the default program name, I made it configurable and it defaults to the original value (rst2html5) but this probably only works on Fedora by default (?)
- I would think doc should be auto rebuilt / cleaned with make all/make clean - however, since the html output and others is dependent on a lot of things i didnt add that yet
- consequently my cheatsheet.rst.html document might be slightly different from yours and you might want to run make doc again :/
- /!\ :warning:  the file in doc/.files/createdb.sh seems to be missing from the tree so the doc building doesn't 100% succeeds. I suppose you have it locally @jvehent

Allow building doc from top level dir, add cheatsheet

---

Makefile
doc/Makefile
doc/concepts.rst
doc/concepts.rst.html
doc/configuration.rst
doc/configuration.rst.html
doc/worker_mozdef_asset.html
src/mig/event/event.go
src/mig/scheduler/agents_queues.go
src/mig/scheduler/context.go
src/mig/scheduler/events.go
src/mig/workers/agent_verif/main.go
src/mig/workers/mozdef_asset/doc.rst
src/mig/workers/mozdef_asset/main.go
src/mig/workers/workers.go

This patch implement a new rabbitmq exchange called migevent where
the scheduler publishes any event of interest. Workers can subscribe
to specific events using binding keys (standard rabbitmq topic
exchange). A simple mozdef-asset worker is implemented, and the base
for an agent verification worker is also present but not yet functional.

[major] Implement support for event workers

---

conf/available_modules.go
src/mig/modules/timedrift/doc.rst
src/mig/modules/timedrift/timedrift.go

This module performs NTP requests to compare the local time of a system with network time, and verify that systems are in proper sync with NTP.
System non-compliant with a 10 milliseconds drift from NTP.
```
$ mig timedrift -t "name='fedbox2.jaffa.linuxwall.info'" -show all -drift 10ms 2>/dev/null
stat: execution time 252.902127ms
fedbox2.jaffa.linuxwall.info local time is 2015-03-14T13:26:27.441740604-04:00
fedbox2.jaffa.linuxwall.info local time is out of sync from NTP servers
fedbox2.jaffa.linuxwall.info Local time is ahead of ntp host 0.pool.ntp.org by 17.731324ms
fedbox2.jaffa.linuxwall.info Local time is ahead of ntp host 1.pool.ntp.org by 16.542859ms
fedbox2.jaffa.linuxwall.info Local time is ahead of ntp host 2.pool.ntp.org by 20.853337ms
fedbox2.jaffa.linuxwall.info Local time is …
```

Timedrift module

---

src/mig/modules/netstat/netstat_darwin.go

I tested this by hand on OS X 10.8.
I did run into some trouble, indicated by the comments inline, where netstat produces a truncated ipv6 address.  I don't have any idea how to fix that, or if it's even possible.

Bug 104714: implement HasIPConnected on Darwin

---

Makefile
conf/available_modules.go
src/mig/modules/memory/doc.rst
src/mig/modules/memory/memory.go
src/mig/modules/memory/memory_test.go
src/mig/modules/memory/params.go
src/mig/modules/modules_test.go

This is a rewrite of #48 to use a logic closer to the `file` module, but for scanning memory. The code works. It needs the params parsers and creator, some documentation and tests.
Here's a sample run, matching a string from an email I have open in one of my firefox tab:
```json
$ sudo ./bin/linux/amd64/mig-agent-latest -m memory <<< '{"class":"parameters", "parameters": { "searches": { "s1": { "names": [ "firefox" ], "contents": ["Michal Zalewski discovered multiple vulnerabilities in SQLite"], "options": { "matchall": true } } } } }' 2>/dev/null | j
{
"elements": {
"s1": [
{
"process": {
"name": "/usr/lib64/firefox/firefox",
"pid": 24767
},
"search": {
"contents": [
"Michal Zalewski discovered multiple vulnerabilities in SQLite"
],
"names": [
"firefox"
],
"options": {
"matchall": true
} …
```

[major] Memory module, using Masche

---

Makefile

Since readline is the last package go-gotten, it appears to users that
the install has failed, and sends them looking for how to install
readline and why the install isn't working, when in fact the go module
has installed just fine.
This uses a little make trickery to not give any indication that
anything's wrong unless the install fails.

Hide the notes about readline-devel

---

src/mig/modules/agentdestroy/agentdestroy_test.go
src/mig/modules/example/example_test.go
src/mig/modules/file/file_test.go
src/mig/modules/memory/memory_test.go
src/mig/modules/netstat/netstat_test.go
src/mig/modules/ping/ping_test.go
src/mig/modules/timedrift/timedrift_test.go
src/mig/modules/upgrade/upgrade_test.go
src/mig/testutil/modtest.go

This adds a test script for each existing module, which just verifies that it's registered and that the registered function returns an object that can be cast to the `modules.Moduler` interface.  Baby steps :)

factor out testing for correct module registration

---

Makefile

This searches recursively for tests under mig/modules, so we automatically get all modules tested -- no accidentally forgetting to add your test suite to the Makefile and getting incorrect green builds from Travis!

run all module tests, rather than naming them individually

---

Makefile

This just saves a little time when I want to run 'make all' repeatedly

Add an all-but-deps make target to skip the go-get-deps part

---

Makefile
action.go
client/client.go
client/mig/main.go
conf/runner.cfg.inc
doc/runner.rst
mig-runner/context.go
mig-runner/entity.go
mig-runner/main.go
mig-runner/plugin.go
mig-runner/results.go
pgp/sign.go
runner.go
vendor/github.com/gorhill/cronexpr/APLv2
vendor/github.com/gorhill/cronexpr/GPLv3
vendor/github.com/gorhill/cronexpr/README.md
vendor/github.com/gorhill/cronexpr/cronexpr.go
vendor/github.com/gorhill/cronexpr/cronexpr/README.md
vendor/github.com/gorhill/cronexpr/cronexpr/main.go
vendor/github.com/gorhill/cronexpr/cronexpr_next.go
vendor/github.com/gorhill/cronexpr/cronexpr_parse.go
vendor/github.com/gorhill/cronexpr/cronexpr_test.go
vendor/github.com/gorhill/cronexpr/example_test.go

this pr adds mig-runner for action scheduling and automated results processing.

mig runner action scheduling

---

Makefile
client/mig-action-generator/generator.go
client/mig-action-verifier/verifier.go
client/mig-console/console.go
client/mig/main.go
mig-agent/agent.go
mig-api/api.go
mig-runner/main.go
mig-scheduler/scheduler.go
modules/file/paramscreator.go
version.go
workers/mig-worker-agent-intel/main.go
workers/mig-worker-agent-verif/main.go
workers/mig-worker-compliance-item/main.go

In [bug 1207709](https://bugzilla.mozilla.org/show_bug.cgi?id=1207709), we noted that the `version` string isn't set when installing binaries using `go get`. This patch sets a base version string the MIG package, which is modified when binaries are built using the Makefile. The trade-off is that we'll need to update the base version string on a regular basis.
```
$ make
$ for bin in $(ls bin/linux/amd64); do echo -en "$bin: "; ./bin/linux/amd64/$bin -V; done|column -t
mig:                             20150924+11e33fc.dev
mig-action-generator:            20150924+11e33fc.dev
mig-action-verifier:             20150924+11e33fc.dev
mig-agent-20150924+11e33fc.dev:  20150924+11e33fc.dev
mig-agent-latest:                20150924+11e33fc.dev
mig-api:                         20150924+11e33fc.dev …
```

Improve the way version numbers are managed, fixes 1207709

---

client/client.go

When building client transport, include OS related proxy configuration so client can make use of it

[minor] honor os proxy environment variables in client

---

modules/file/doc.rst
modules/file/file.go
modules/file/paramscreator.go

If the -hash option is present, include the SHA256 sum of the matched
file as part of the file info.
This is intended to be used for example with broad searches as a source for integrity monitoring across multiple runs.

[minor] add optional hashing for file module results

---

client/client.go

When the .migrc is missing, a new one can be created, and if gpg is
installed, but there is no suitable key in the secring file, it will
display an error saying "No suitable key found". This commit also adds
to the error description the file which was inspected.
This fixes issue #132.

[client] better description on gpg key not found

---

mig-agent/agent.go
mig-agent/env.go

There was an ioutil.WriteFile whose permissions were not in octal, giving
the resulting file bad permissions.
This commit also changes some of the printf formats from '%s' to %q,
which already quotes the desired variable.

[minor] fix permissions bug on receiveModuleResults in mig-agent

---

mig-agent/agent.go

The comment said "if in foreground mode, don't retry, just panic", but
the if condition only checked for debug, no foreground.
debug -> foreground, but you can run the mig agent in foreground without
debug mode.

[minor] panic on agent init err if foreground mode

---

mig-agent/agent.go
mig-agent/config.go

If an error ocurred during configLoad function, it might not use the
builtin conf, but a half-overwritten one. This change defers the
Config overwrite until all the error-sensitive functions are called.

[minor] fix configLoad bug in mig-agent

---

.travis.yml
mig-agent/agent.go

To make the code more easy to follow, I moved the logic for
loading/running an action from a file into it's own function
"loadActionFromFile"
Also move the "debug-mode" switch to after loading the mig configuration,
because loading the configuration overrides the LOGGINGCONF variable

Minor refactor on mig-agent startup

---

modules/netstat/netstat.go
modules/netstat/netstat_linux.go
modules/netstat/paramscreator.go

@gdestuynder @jvehent please review when possible
This patch adds support to the netstat module to identify network activity in other namespaces granted the agent is running with access to a global PID namespace. Currently in the netstat module, MIG can only see network activity related to the namespace it runs in.
This support has been added as an option, to maintain the existing behavior. Ideally we would change it to the default at some point.
One caveat is local interface MAC detection does not support this new functionality as we are using go net.Interfaces() here vs. inspecting the system directly in HasLocalMAC(). This function would need to be changed to support this. However other MAC detection (e.g., neighbor MAC) works as expected.

namespace support in netstat module

---

constants.go
mig-scheduler/context.go
mig-scheduler/events.go
mig-scheduler/routines.go
version.go

If RabbitMQ suffers a network partition, the scheduler will remain in a half broken state where no message can be consumed or published, but other goroutines work fine. This patch introduce a new dummy event that heartbeats the scheduler and terminates it if the publication of the heartbeat fails. The hearbeat is a normal event that expires in rabbitmq after 100 minutes, like any other event. It is published to a queue that could eventually be consumed for monitoring.
r? @ameihm0912

Scheduler relay heartbeat

---

agent.go
conf/mig-agent-conf.go.inc
mig-agent/aws.go
mig-agent/config.go
mig-agent/context.go
tools/standalone_install.sh

This change adds support for discovery of specific elements of instance metadata by agents running in AWS. Fetched metadata is included in the agents environment.

[medium] Support fetch of instance meta-data for agents running in AWS

---

actions/linux-backdoor-kanada-team-binaries.json
actions/linux-backdoor-kanada-team-short.json
actions/linux-backdoor.json
actions/shellshock_iocs.json
actions/sshd_backdoor.json
doc/module_file.html
mig-api/compliance.go
modules/file/doc.rst
modules/file/file.go
modules/file/file_test.go
modules/file/paramscreator.go
runner-plugins/runner-compliance/main.go

I tried fusing the hashes under sha2/sha3 as we discussed on IRC, but the tests aren't passing.
[Here](https://gist.github.com/therealkbhat/b2ffffa2e2ef7e22c9f3) is the error log.
So, this is a WIP, with the following points to be addressed:
* I need a bit of help on figuring out what's wrong with my code.
* I need to add more test cases to ensure that every way the "-sha2" and "-sha3" flags (with hashes of varying length) can be used are indeed tested.
Thanks in advance for your feedback!

[medium] Unify hash selection under sha2/sha3; fixes #155

---

doc/module_file.html
modules/file/doc.rst
modules/file/file.go
modules/file/file_test.go
modules/file/paramscreator.go

Work in progress.
`decompressFile` returns a file descriptor which gets passed to `checkContent` and `checkHash` from `evaluateFile`. Note that I haven't removed `file string` from those calls; it seemed less invasive to pass both the string as well as the file descriptor, especially since the string is used extensively in calls to `debugprint` and `storematch`.
Does leaving the fd open across multiple function calls (`checkContent`, all the `checkHash`s) lead to any problems?
I haven't gotten to tests or doc changes yet; thought I'd get feedback on this approach first. I also still need to look at dealing with multiple files in a single zip.

[medium] Decompress files before content inspect, resolves #108

---

modules/netstat/netstat_darwin.go
modules/netstat/netstat_windows.go

These functions need to be implemented, but this fixes current build
errors on these platforms.
Closes #199

[minor/bug] add stub functions for HasSeenIP for darwin and windows

---

mig-scheduler/agents_management.go
mig-scheduler/agents_queues.go
mig-scheduler/routines.go
mig-scheduler/scheduler.go

Removes upgrade module code in the scheduler.
Ensure we drain DetectDupAgents even if the option to kill duplicate agents is disabled in the scheduler configuration. There are a few places in the code we write to this channel, currently if the option is disabled the receiving end will not be spawned. This leads to routines in the scheduler blocking when they write here. We already check the configuration in the agent kill function in the scheduler, so just drain the channel and call this function and it is handled there depending on the setting.

fixes to scheduler

---

client/client.go
loader.go
mig-api/api.go
mig-loader/loader.go

This also resolves an issue in the client library on 401 re-request where the body was not being read prior to submitting the request again.

Minor improvements to loader API authentication

---

client/mig-console/manifest.go
doc/loader.rst
manifest.go
mig-loader/loader.go

This removes support for the per-loader relay credentials, and functions that transform the agent configuration file. The configuration file is treated like the other objects in the manifest now. The reduces the complexity associated with deploying the loader, as the cost of having a shared credential for rabbitMQ amongst agents deployed using the manifest.
This also adds support for fetching the manifest for review using mig-console.

Remove per-loader relay credentials

---

conf/mig-agent-conf.go.inc
conf/mig-agent.cfg.inc
doc/configuration.rst
mig-agent/agentcontext/env.go
mig-agent/config.go
mig-agent/context.go
tools/standalone_install.sh

If any proxies have been configured, try those first before attempting
direct connections. This also adds specifying proxies in the agent
config file, where as before they were only compile time options in the
built-in configuration.
Resolves #249

[medium] change agent proxy behavior to prefer proxies

---

client/mig-agent-search/main.go
database/searches.go

Rather than only supporting search via a targeting string, add a second mode that allows for agent queries that could include agents we wouldn't return during target evaluation. This can be used to list all agents known to the API.

Enhancements to mig-agent-search

---

conf/api.cfg.inc
doc/api.rst
doc/configuration.rst
mig-api/api.go
mig-api/context.go

See #247 for details
Currently, if the API sees an X-Forwarded-For header, it will implicitly use this value over the peer address. This can cause issues in a scenario where the API is listening for connections directly on a non-SSL port, and an intermediate proxy is used by an agent. This results in the incorrect public IP being returned to the agent.
This adds a configuration option to the API to indicate if the API should honor the XFF value, or if it should use the peer address, which can be toggled depending on how it is deployed.
The default setting is off (do not use X-Forwarded-For) as the API alone operates in this manner, even though it is unlikely to be deployed like this, but this works with the standalone install.

Improve handling of X-Forwarded-For value in API

---

.travis.yml
client/client.go
client/macro.go
client/mig-console/action_launcher.go
client/mig/main.go
conf/migrc.inc
doc/configuration.rst
doc/console.rst

This provides the ability for users to define target macros in ~/.migrc,
as an example rather than requiring -t "status='online'", given a
section such as:
[targets]
macro = allonline:status='online'
in .migrc, you can then do -t allonline. The intended specification
format is macro = name:target string. Multiple "macro" items can be
specified in the targets section.

[minor] add support for user defined target macros

---

mig-api/manifest_endpoints.go

Set our own limit on body read size here since the file uploads can exceed the default.

[minor/bug] permit larger form sizes for manifest uploads

---

client/client.go
client/mig-console/loader.go
database/loader.go
database/schema.sql
doc/loader.rst
loader.go
mig-api/api.go
mig-api/manifest_endpoints.go

Adds ability to specify an expected environment or tag query string to
loader instances which are verified prior to manifest lookup.
Resolves #255

[medium] add environment validation to loader authorization

---

client/client.go
client/mig-console/investigator.go
client/mig-console/search.go
database/investigators.go
database/schema.sql
database/searches.go
doc/console.rst
doc/loader.rst
investigator.go
mig-api/api.go
mig-api/investigator_endpoints.go
tools/standalone_install.sh

This removes the previous implementation where an investigator could
either be set to an admin or not, and expands this to per-endpoint
permissions that can be set for individual investigators.

[medium] more granular permissions for investigators

---

conf/mig-agent-conf.go.inc
conf/mig-agent.cfg.inc
doc/configuration.rst
doc/modules.rst
mig-agent/agent.go
mig-agent/config.go
modules/file/file.go
modules/modules.go
modules/netstat/netstat.go
modules/scribe/scribe.go
tools/standalone_install.sh

Adds an extra privacy mode configuration option to the agent which provides data masking beyond the privacy protections that already exist in MIG. With this option enabled, modules which honor the flag will mask certain meta-data in the responses.
Implemented for the file module, netstat module, and scribe module.

Implementation of agent EPM

---

mig-agent/agentcontext/env_linux.go

Changes the way the hostname is acquired on Linux
- Kernel hostname is preferred over DNS
- Full FQDN from DNS is used if the first component matches the kernel hostname

Modify agent context findHostname() behavior on Linux

---

client/client.go
client/mig-agent-search/main.go
client/mig-console/console.go
client/mig/main.go

Not intended for use in the general case, but permits using various mig
command line tools in an automated manner more easily.

[minor] support passphrase input via env

---

acl.go
action.go

This patch fixes a security issue in the ACL verification code
that allows a single investigator to sign an action multiple
times in order to meet the threshold required to run the action.
Given the lack of support for multiple signatures in the client
code until recently, and the fact the investigator still has to
be authorized to run the module anyway, this is considered MEDIUM.
r? @ameihm0912

[medium/bug] Prevent one investigator from signing multiple times

---

tools/osx-loader-pkg-postinstall.sh

Validates key is correct format before using it on OSX.
Fixes #202

[minor] validate key format on osx loader installation

---

conf/available_modules.go
conf/mig-agent-conf.go.inc
conf/mig-agent.cfg.inc
doc/modules.rst
doc/modulespersist.rst
mig-agent/agent.go
mig-agent/config.go
mig-agent/persist.go
modules/examplepersist/examplepersist.go
modules/examplepersist/examplepersist_test.go
modules/examplepersist/paramscreator.go
modules/modules.go
tools/standalone_install.sh

Adds support for persistent modules.
Persistent modules can be used to run background tasks in the agent as a separate process which is managed and kept alive by the agent. The modules run and can keep state over their lifetime, and can be used to perform investigative related tasks across time or execute other continuous functions.
Persistent modules can be queried in the same manner as regular modules using mig-cmd or mig-console. The Run() entry point is still used, but rather than return a result string this function instead interfaces directly with the running module over a domain socket. This removes any need to multiplex requests to the module in the agent itself, runModuleDirectly() is still used for a request which interfaces with the domain socket the persistent module …

Persistent module support

---

mig-agent/agentcontext/env_windows.go

use C:\mig instead of C:\Program Files\mig\
closes #282

[minor] windows fix agent path

---

mig-agent/config.go
mig-agent/config_test.go

support blank values for certs
report offending config fields in parseConfig errors
add Globals struct for mapping traceability to global vars and testing
unit tests
closes #281

[minor] improve agent config parsing and errors

---

client/mig/main.go
mig-agent/agent.go
mig-agent/persist.go
modules/agentdestroy/agentdestroy.go
modules/example/example.go
modules/examplepersist/examplepersist.go
modules/file/file.go
modules/file/file_test.go
modules/memory/memory.go
modules/memory/memory_test.go
modules/modules.go
modules/modules_test.go
modules/netstat/netstat.go
modules/ping/ping.go
modules/pkg/pkg.go
modules/scribe/scribe.go
modules/timedrift/timedrift.go
modules/upgrade/upgrade.go

When a message between a module and the agent is read by either,
ReadInput is used which uses buffered IO to read a single line. A bug
existed here where a new bufio Reader was being allocated each time.
Under normal circumstances there would be no issue, since a single line
is generally sent to the module from the agent and read. However, in a
case where a large number of messages were being exchanged between the
agent and the module (e.g., persistent modules) it was possible the
bufio reader could have buffered more than one line. Since a new buffer
was being allocated each time, this resulted in loss of partial message
data, and usually ended up generating JSON unmarshaling errors since
part of the JSON structure was missing.
This was resolved by introducing a new ModuleReader and …

[medium/bug] resolve bufio issues under high agent/module comms

---

conf/mig-agent-conf.go.inc
mig-agent/config.go
mig-agent/configuration.go
mig-agent/persist.go
modules/examplepersist/examplepersist.go
modules/modules.go
tools/standalone_install.sh

Adds the ability for persistent modules to read a configuration file
that can be used to control their behavior.
In some cases, we may want a persistent module to be configurable. A new
configuration variable PERSISTCONFIGDIR has been added which indicates a
directory the agent will look in for persistent module configs. When the
agent starts a persistent module, it will determine if modulename.cfg
exists in the config directory; if so the agent will load the config and
send it to the newly executed module, which it will read on stdin. The
module can then read this configuration, and configure itself as needed
before it begins it's primary execution functions.
Modules specify the configuration format within the module code itself,
so each module that makes use of this can have it's own …

[medium] persistent module config file support

---

.travis.yml

Enables all modules, including non-default modules as part of travis
tests.

[minor] when travis tests run, enable all modules

---

client/mig-console/investigator.go
doc/api.rst

setadmin in mig-console was replaced by setperms; remove an old
reference to it in the help output. Also removes some references to
isadmin that were still present in API documentation.
Closes #312

[minor] remove reference to setadmin from mig-console

---

agent.go
conf/scheduler.cfg.inc
database/agents.go
database/loader.go
database/schema.sql
mig-agent/agentcontext/agent-context.go
mig-agent/context.go
mig-scheduler/context.go
mig-scheduler/logging.go
mig-scheduler/scheduler.go

Adds an option to the scheduler to log a summary of each command dispatched to an agent. This summary will include the name of the loader instance associated with the agent, if one is present.
To do this, agent ID (e.g., .migagtid) related functionality was moved into agentcontext so it could be used by both the loader and the agent. The loader now sends the agent ID with its requests, which will be the same ID the agent is using for queue location to allow correlation between the instances.

Better correlation between loader/agent instances and action logging

---

mig-agent/agent.go
mig-agent/context.go
mig-agent/socket.go

Converts existing status socket to use HTTP, updates behavior of -q to make HTTP requests, addition of a status page at / that displays various agent configuration for now.

Use HTTP for status socket, add agent status page

---

client/mig/main.go

ba34c5c moved some code in mig-cmd around so a client/configuration was
not required with -t local, but this created issues with -i as the
configuration was no longer being read. Update action file handling to
include reading configuration and creating a client.

[minor/bug] read conf and create client in mig-cmd with -i

---

conf/mig-agent-conf.go.inc
conf/mig-agent.cfg.inc
mig-agent/agent.go
mig-agent/config.go
mig-agent/configuration.go
mig-agent/context.go
mig-agent/socket.go
mig-agent/stats.go
tools/standalone_install.sh

Agent tracks some basic stats on the last 15 actions it has received and provides details on these via the status socket. This includes if the action was processed or not.
Currently this is limited to in-memory stats which would be lost on restart, but the intent is it can be adapted to make use of local storage for persistence if needed.

[minor] include recent actions in agent statistics output

---

mig-agent/socket.go

If the agent fails to bind the status socket, it will wait and retry
again. As part of this retry, it was also binding endpoints to register
them in the http package for the status socket which would result in a
panic.
Changes behavior so endpoints are only registered once.

[minor/bug] register endpoints on status socket once

---

mig-agent/context.go

When the agent shuts down (e.g. due to a signal, etc) a message is sent
to the Terminate channel, which results eventually in the agent Context
being destroyed.
The terminate channel was being closed before the AMQP connection was
being shut down. This was causing a panic as the getCommands function
also writes to the terminate channel to indicate relay collection is
failing.
Move close of Terminate later in destroy and after we shut down the AMQP
connection so prevent the write on the closed Terminate channel in
getCommands.

[minor/bug] resolve write to closed chan Terminate panic on shutdown

---

client/client.go
client/mig-console/investigator.go
database/investigators.go
database/schema.sql
database/searches.go
doc/api.rst
doc/console.rst
investigator.go
loader.go
mig-api/api.go
mig-api/apikey.go
mig-api/investigator_endpoints.go
mig-api/manifest_endpoints.go
mig-api/pgp.go
mig-scheduler/pgp.go
misc.go
tools/standalone_install.sh

Adds support for using a standard API key where required to access the MIG API. This essentially adds an alternative to using X-PGPAUTHORIZATION which may be more easily utilized for integration of external applications with the API.
Note: this changes nothing related to action signing and interrogating agents, and is solely utilized for simplified access to functions the API provides itself.

Support API key authentication for mig API

---

logging_windows.go
mig-loader/loader.go
mig-loader/svc_windows.go

Resolves an issue with Windows logging where rotation fails on this platform due to the file being open when we attempt to rename it.
This also adds the `-c` flag to mig-loader, which instructs the loader to just check if the agent is running and not to do a full manifest compare. This is used in the loader Windows service to periodically check the status of the agent.

Fix bug in Windows logging, add check option to loader

---

mig-agent/agentcontext/env.go

Reduce the dial timeout to 5 seconds time 10. This operation should
normally occur quickly, but in some cases (e.g., an unreachable proxy in
use) the request will stall. This ensures we wait a maximum of 5 seconds
before trying another option.
This also aligns the timeout with the dial timeout for AMQP connections.

[minor] findPublicIP: reduce Dial timeout to 5 seconds

---

conf/mig-agent-conf.go.inc
conf/mig-agent.cfg.inc
conf/mig-loader-conf.go.inc
mig-agent/config.go
mig-agent/configuration.go
mig-loader/configuration.go
tools/standalone_install.sh

Apologies in advance, my go experience is limited at this point so any feedback is constructive!
Currently tags can only be set in the build of the agent binary. Portions of the agents configuration can be set in an external file, so I just added the ability to set tags in that file. The tags are in essence configured as a list of key value pairs separated by colon. At init the tags are parsed and set. Tags set externally are merged with the `TAGS` set in the agent and can be accessed using the new method, `GetTags()`
Tags can be set in this fashion.
```
[agent]
; Tag the instance with attributes to filter investigation scope
tags = "operator:Ops_Emea"
tags = "role:web"
```

[minor] Adding option to set agent tags in external config file

---

CONTRIBUTING.md

This removes any sort of requirement to prefix commit messages from the
contributing guidelines. This was originally intended to provide a means
to identify large changes/feature additions in the revision history.
Removing this to make it easier for contributors to submit patches
without requiring history revision.

update CONTRIBUTING.md, remove requirement to tag commits

---

mig-agent/agent.go
mig-agent/context.go

In checkin mode, make sure a non-zero exit status is returned if the agent fails to start up.
This also changes the way failures from Init are handled in foreground mode, so the agent exits cleanly with an error message rather than a panic.

Fixes a few issues in how Init failures are handled

---

runner-plugins/runner-scribe/main.go
vendor/github.com/jvehent/gozdef/vulnevent.go

Updates from gozdef and scribe-runner plugins changes to set a zone name, which is a required field

Minor fixes to scribe event submission

---

modules/file/file.go

If a file symlink existed in the root of a search path (e.g., /tmp was
being searched and /tmp/file was a symlink) path separators were not
being added correctly, resulting in no separator between the directory
path and the file name.
This caused subsequent checks (e.g., trying to follow and open the
symlink for content inspection) to fail, resulting in errors being
included in the module error log.

file: don't skip adding path separator if directory entry is a symlink

---

modules/file/file.go

Don't use MaxErrors from the matched file var, as the Search field has
not been set here. Use MaxErrors from the parent Search type we are
currently inspecting checks for instead.

file: fix bug with maxerror handling when matchall was false

---

modules/file/file.go
modules/file/file_test.go

In addition to the tests, also adds masking on walking errors in the module result.

Adds tests for file modules privacy mode

---

modules/file/file_test.go
vendor/github.com/mozilla/masche/listlibs/listlibs_darwin.go
vendor/github.com/mozilla/masche/memaccess/memaccess_c_wrapper.go
vendor/github.com/mozilla/masche/process/process_c_wrapper.go

Update the file test so it resolves the symbolic link path used for the test base directory, since on Darwin the path returned by TempDir is a symlink. This ensures the correct path is used when comparing the results of the various tests.
Also update masche library, which contains fixes preventing build on Darwin with memory module support.

Fixes for tests and build on Darwin

---

client/client.go

Some calls to GetAPIResource are not validating the error return.

client: check error result on GetAPIResource

---

client/client.go

This reverts the change made in 32824ce2 to handle error results from
GetAPIResource. Some logic in here needs to be revisited; GetAPIResource
returns an error even under normal circumstances (such as getting a 404
if no results were found for a given query) which breaks results fetch
in the client.

client: revert GetAPIResource change made in 32824ce2

---

doc/configuration.rst

Add a reference to the modulepack package in the configuration guide
that can help determine what tags to use to get certain module
configurations in the agent and clients.

doc: include a reference to modulepack in the config guide

---

mig-agent/agent.go
mig-agent/agentcontext/agent-context.go

Fixes a bug where string concatenation was being used construct the path to the agent ID file, which could cause problems if the path did not explicitly end in a directory separator (e.g., /), instead use the standard path join function

agent: use path.Join instead of string concat to construct agtid/ok

---

acl.go
acl_test.go
action.go
action_test.go
mig-agent/context.go

This change removes the Permission type, and modifies ACL to simply be a
map of a given module name and the authorization specification.
It was previously stored as a list of ACL types, with each type being a
map which was not required.
This also fixes a bug in authorization, where an action would be
authorized if the first operation validated against the ACL. This means,
it was possible if an action contained more than one operation, an
investigator could be authorized for execution if the first module
matched the ACL. Note that for this to happen, the first operation
checked would need to be authorized and in general deployments this does
not have a significant impact.
Resolves #394

simplify ACL type and remove Permission, fix authorization bypass

---

README.md

The standalone install script is no longer present in the repository and
has been replaced by the docker image; also update the docker section.

update README, remove references to standalone install script

---

acl.go
action.go
agent.go
command.go
constants.go
investigator.go
loader.go
logging_posix.go
logging_windows.go
manifest.go
mig-agent/agent.go
mig-agent/context.go
mig-scheduler/agents_queues.go
mig-scheduler/context.go
mig-scheduler/scheduler.go
runner.go
version.go

Fix a bunch of godoc issues, removes exchange and queue names which were
no longer being utilized, and the GenB32ID function which was also not
being used. Renames some constant values to remove mixture of all caps
and underscores in constants.

style related code cleanup in mig top-level package

---

CNAME

This PR removes the CNAME file reference from the mig github page.  The intent of this change is to frontend mig.mozilla.org with a CloudFront Distribution with the github page set as an origin.  In such a model, the CNAME claim in github is no longer relevant (in fact it's a hinderence) because calls from CloudFront will actually be pulling this content over mozilla.github.io/mig rather than mig.mozilla.org and CloudFront will be the frontend as mig.mozilla.org.
This is associated with work in https://bugzilla.mozilla.org/show_bug.cgi?id=1438966 and merging it will need to be syncronized with DNS re-pointing from github to the cloudfront distribution in Route53.

Remove CNAME file in prep for Cloudfront distribution

---

contribute.json

JSON is not as forgiving as Ruby Hash I guess

Fix some validation errors with contribute.json

---

acl_test.go
action.go
action_test.go
client/mig-console/action_launcher.go
client/mig-console/investigator.go
client/mig-console/search.go
mig-api/action_endpoints.go
mig-scheduler/pgp.go
modules/agentdestroy/agentdestroy.go
modules/file/file_test.go
modules/file/paramscreator.go
modules/memory/params.go
modules/ping/paramscreator.go
pgp/verify.go

As I reported in #437, I was seeing some errors after running `make test` that were causing tests to fail.  These errors are extremely simple format string issues which seem to be being handled more strictly in more recent versions of Go (I'm using 1.10).
I'd like some feedback about how to proceed from where this PR would leave us.  My commit here fixes the format string errors I encountered, however I am now seeing some different errors. These ones appear to be more critical issues relevant to the actual function of MIG.  I would hate to submit a PR that still has errors, but hope we can discuss how to proceed. It may be desirable to use the branch I've created as a pivot around which we'll commit more fixes before merging into `master`.
```
OOS=darwin GOARCH=amd64 …
```

Fixed format string errors that were blocking make test

---

.travis.yml
aws/releases-cloudtrail-build-user.yml

This PR includes:
* A CloudTrail stack (courtesy of @andrewkrug) that creates an IAM user specifically for managing the S3 bucket we want to deploy to along with a managed policy for that user
* An updated `.travis.yml` file containing an encrypted secret (and its corresponding ID) owned by the user created by the CloudTrail stack
These changes should make it possible for Travis to push builds to the S3 bucket we have created.

Setting up an S3 bucket safely

---

database/database.go
mig-api/context.go
mig-scheduler/context.go

This improves troubleshooting, or else the connection seems to be established, but realistically, no connection attempt was made, the open() function only checks syntax of the db string.

Add check for ping during postgresql connection

---

runner-plugins/runner-scribe/main.go

~This PR is dependent on the [oustanding PR for gozdef](https://github.com/jvehent/gozdef/pull/6) to add support to disable the use of a proxy in Gozdef.~
Julien has stated that he no longer intends to maintain gozdef, so I guess I'm inheriting it.  I've forked it to `mozilla/gozdef` and pushed my changes right into master.

Adding support for proxy disabling in gozdef

---

runner-plugins/runner-scribe/main.go
runner-plugins/runner-scribe/main_test.go

I couldn't really find a way to write tests for this effectively.  For now I want to get this change merged up to see how it affects mig-runner in production and whether more extensive testing is going to be necessary.  The hope is that this will resolve the issue of runner-scribe exiting with a status code of 1 even when it appears to "work".

Always set SourceName to 'mig-runner'

---

runner-plugins/runner-scribe/main.go
runner-plugins/runner-scribe/main_test.go

This restores long-desired functionality to query ServiceAPI for an Operator and Team and then publish those to the vulnerability event being posted to MozDef.
Specifically we:
1. Get an authentication token from Auth0
2. Get all assets that ServiceAPI knows about and store them in a searchable map, keyed to hostname
3. As we encounter a host with vulnerabilities, we lookup operator and team and append them to the vulnerability event. If operator and team are not found in the ServiceAPI data, we set operator based on the config of the agent. Team remains blank.

Query ServiceAPI for Operator & Team

---

Makefile

This PR is a work in progress. Please do not review or merge it until the WIP status is revoked.
At Mozilla, we have encountered an issue with agents in production wherein updates fail due to hanging `systemctl stop` processes.  In order to be able to cleanly reinstall the agent on a host in such circumstances, we need to kill these hanging processes. We also opt to remove the `/etc/mig` directory and its contents as well as the agent's Unit file.  By doing so, automated processes using tools such as Ansible can more-or-less blindly recreate these resources using the latest versions of them, facilitating a smooth re-install.

Clean up SystemD agents for smooth re-installs
