src/mig/agent/socket.go
=> [major/bug] prevent socket stat from locking agent results publication

Makefile, actions/integration_tests.json, conf/available_modules.go, src/mig/modules/ping/doc.rst, src/mig/modules/ping/paramscreator.go, src/mig/modules/ping/ping.go
Review in progress. See https://bugzilla.mozilla.org/show_bug.cgi?id=1068851
=> Ping module

src/mig/agent/agent.go, src/mig/api/compliance.go, src/mig/client/client.go, src/mig/client/cmd/main.go, src/mig/client/console/action_launcher.go, src/mig/modules/file/file.go, src/mig/modules/modules.go, src/mig/scheduler/scheduler.go, src/mig/workers/compliance_item/main.go
Updates so file module works with stdin parameter submission, and other fixes so the entire tree builds
=> [major] various fixups for recent stdin changes

src/mig/agent/agent.go, src/mig/client/cmd/main.go
Some various fixes I'm just adding as I go, feel free to grab anything that is useful.
=> General fixes

Makefile, doc/modules.rst, doc/modules.rst.html, src/mig/agent/agent.go, src/mig/modules/agentdestroy/agentdestroy.go, src/mig/modules/example/example.go, src/mig/modules/file/file.go, src/mig/modules/modules.go, src/mig/modules/modules_test.go, src/mig/modules/netstat/netstat.go, src/mig/modules/ping/ping.go, src/mig/modules/timedrift/timedrift.go, src/mig/modules/upgrade/upgrade.go
Refactoring of the module interfaces to supports testing, and unit tests for the whole `mig/modules` package.
=> Modules tests

doc/agent.rst, doc/modules.rst
The module initialization process is pretty convoluted, and the docs didn't quite match reality.  This adjusts the docs to match reality.  I'll loop back in later PRs and make reality a little more sane.
=> Modules doc fix

src/mig/modules/pkg/doc.rst, src/mig/modules/pkg/paramscreator.go, src/mig/modules/pkg/pkg.go
Added documentation, ParamsCreator(), and some cleanup.
=> pkg module documentation, and some additional cleanup

src/mig/modules/pkg/pkg.go, src/mig/modules/pkg/pkg_test.go
Add a parameters test for pkg module, and some additional parameter validation
=> [minor] parameter tests for pkg module, and some additional validation

src/mig/client/client.go
Should match mozilla/server-side-tls#69
=> [minor] Update cipher ordering

AUTHORS, CONTRIBUTING.md
=> [doc] contributing guidelines

doc/cheatsheet.rst, doc/cheatsheet.rst.html
Note: the html file may need regeneration with ulfr's setup for consistency. I generated it with my system and notice subtles diffs in the css styles from my version of docutils :(
=> Add instructions on how to directly invoke mig-agent

README.md, client/mig/main.go, doc/Makefile, doc/agent.rst.html, doc/api.rst.html, doc/cheatsheet.rst, doc/cheatsheet.rst.html, doc/concepts.rst.html, doc/configuration.rst.html, doc/data.rst.html, doc/docstyle.css, doc/mig-worker-agent-intel.html, doc/mig-worker-compliance-item.html, doc/module_file.html, doc/module_memory.html, doc/module_ping.html, doc/module_pkg.html, doc/module_scribe.html, doc/module_timedrift.html, doc/modules.rst.html, modules/file/doc.rst, modules/file/file.go, modules/file/file_test.go, modules/file/paramscreator.go
Several file module improvements to make more complex inspections of file systems.
=> File module improvements

mig-scheduler/routines.go
This resolves an issue where large volumes of commands being processed
at the same time could result in the commands being dropped by the
scheduler, due to overflows in the parameter lists during SQL statement
creation.
@jvehent r?
=> [minor/bug] under scheduler load dequeue command batches periodically

doc/cheatsheet.rst
NOTE @jvehent : This needs a new generation of the html file as well, since as usual - we don't have exactly the same versions/files for the rendered and I don't wanna clobber everything.
(if you have a solution for that.. ;)
=> [doc] Added example to look for a user's processes/connected

modules/timedrift/timedrift.go
This pull request fixes #116. Instead of randomly picking an ntp server out of a list of hardcoded ones we now try all the servers in `/etc/ntp.conf` first, and then move onto the hardcoded list.
=> Use servers in /etc/ntp.conf for timedrift

mig-agent/agent.go
This resolves a bug introduced in e2e687f. The args parameter to
runModuleDirectly() used to contain input parameters, but as of recent
changes to allow parameters via stdin does not.
Since the parameter was unused, this changes it to be an interface
pointer. If set, this will be used as module parameters, if not the
agent modules will expect input via stdin as normal.
=> [minor/bug] fix module parameter input issues

mig-agent/agent.go
This patch imposes the same max exec time to the mig agent in checkin mode that we use for modules. If the agent takes longer than MODULETIMEOUT to run, it will be force killed, regardless of pending operations.
This was testing on my dev instance by running a file search on the entire `/` of my local drive.
```
$ sudo ./bin/linux/amd64/mig-agent-latest -m agent-checkin -d
[warn] Could not load a local conf from "/etc/mig/mig-agent.cfg", err: configLoad() -> open /etc/mig/mig-agent.cfg: no such file or directory
[info] Using builtin conf.
.....
2015/11/04 10:54:17 5203168985088 - - [debug] executing module "file"
2015/11/04 10:54:20 - - - [info] No outstanding messages in relay.
2015/11/04 10:54:20 - - - [info] Agent is done checking in. waiting for all modules to complete.
[critical] …
```
=> [medium] Force max exec time for agent in checkin mode, fixes #148

Makefile, modules/pkg/pkg.go, modules/scribe/scribe.go, runner-plugins/runner-scribe/main.go, vendor/github.com/mozilla/scribe/Makefile, vendor/github.com/mozilla/scribe/src/scribe/filecontent.go, vendor/github.com/mozilla/scribe/src/scribe/package.go, vendor/github.com/mozilla/scribe/src/scribe/package_test.go, vendor/github.com/mozilla/scribe/src/scribe/pkgmgr.go, vendor/github.com/mozilla/scribe/src/scribe/result.go, vendor/github.com/mozilla/scribe/src/scribe/test.go, vendor/github.com/mozilla/scribe/src/scribe/vulnpolicy/os.go, vendor/github.com/mozilla/scribe/src/scribe/vulnpolicy/redhat.go, vendor/github.com/mozilla/scribe/src/scribe/vulnpolicy/ubuntu.go, vendor/github.com/mozilla/scribe/src/scribe/vulnpolicy/vulnpolicy.go, vendor/github.com/mozilla/scribe/src/scribecmd/main.go, vendor/github.com/mozilla/scribe/src/scribevulnpolicy/main.go, vendor/github.com/mozilla/scribe/test/filecontent/data/testfile2, vendor/github.com/mozilla/scribe/test/filecontent/test-template.json, vendor/github.com/mozilla/scribe/test/package/test.json, vendor/github.com/mozilla/scribe/test/tags/test-template.json
Not for immediate merge
This branch tracks changes related to the scribe module for the next MIG release; it currently contains a vendored downstream branch which will be removed prior to merge.
=> scribe updates for release

Makefile, client/client.go, client/mig-console/action_launcher.go, client/mig/main.go, vendor/github.com/cheggaaa/pb/.travis.yml, vendor/github.com/cheggaaa/pb/LICENSE, vendor/github.com/cheggaaa/pb/README.md, vendor/github.com/cheggaaa/pb/example_copy_test.go, vendor/github.com/cheggaaa/pb/example_multiple_test.go, vendor/github.com/cheggaaa/pb/example_test.go, vendor/github.com/cheggaaa/pb/format.go, vendor/github.com/cheggaaa/pb/format_test.go, vendor/github.com/cheggaaa/pb/pb.go, vendor/github.com/cheggaaa/pb/pb_nix.go, vendor/github.com/cheggaaa/pb/pb_solaris.go, vendor/github.com/cheggaaa/pb/pb_test.go, vendor/github.com/cheggaaa/pb/pb_win.go, vendor/github.com/cheggaaa/pb/pb_x.go, vendor/github.com/cheggaaa/pb/pool.go, vendor/github.com/cheggaaa/pb/reader.go, vendor/github.com/cheggaaa/pb/runecount.go, vendor/github.com/cheggaaa/pb/runecount_test.go, vendor/github.com/cheggaaa/pb/termios_bsd.go, vendor/github.com/cheggaaa/pb/termios_linux.go
@ameihm0912 : no rush, just a cool little feature.
```
$ mig file -path /home -path /root -maxdepth 5 -name "^config$" -content "(?i)^useroaming no$"
1036 agents will be targeted. ctrl+c to cancel. launching in 5 4 3 2 1 GO
Following action ID 5215088560899.
19 / 1036 [>----------------------------------------------------] 1.83 % 1/s 13s
```
=> [minor] show a pretty progress bar when follow actions in clients

README.md
Ultra minor.
I was going through docs and saw that this needed updating.
=> [minor] Update description of hash inspection capabilities

action.go, client/client.go, client/mig-action-generator/generator.go, client/mig-console/action_launcher.go, client/mig-console/action_reader.go, client/mig/main.go, mig-agent/agent.go, mig-runner/entity.go, modules/file/file_test.go, modules/memory/memory_test.go, modules/modules.go, modules/modules_test.go, modules/scribe/scribe.go
Introduces optional compression of actions between the client and the agents
Compression is specified during action creation and handled when processed by the agent
=> [medium] introduce optional action compression between client and agent

database/commands.go
Move filtering logic added in b3dddf1
=> [minor] Apply filtering in FinishCommand()

client/mig/main.go
Add `-target-foundanything` and `-targetfoundnothing` flags to mig client
=> [minor] Fixes #115

conf/mig-agent-installer.wxs
This PR fixes issue #107 , it's still a work in progress. Right now it only creates the shortcut (it doesn't launch the executable after installing).
=> (WIP) [minor/107] Fix issue #107

mig-scheduler/periodic.go, mig-scheduler/queues_cleanup.go
Resolves a deadlock condition in scheduler periodic run that prevents any future periodic runs from occurring + minor fix related to periodic error checking
=> resolve deadlock in scheduler periodic run

client/client.go, client/mig-console/console.go, client/mig-console/loader.go, client/mig-console/search.go, database/agents.go, database/loader.go, database/schema.sql, database/search/parameters.go, database/searches.go, loader.go, mig-agent/agent.go, mig-agent/context.go, mig-api/action_endpoints.go, mig-api/agent_endpoints.go, mig-api/api.go, mig-api/command_endpoints.go, mig-api/investigator_endpoints.go, mig-api/manifest_endpoints.go, mig-api/search.go, mig-loader/loader.go, mig-scheduler/agents_management.go, mig-scheduler/periodic.go, pgp/keyserver_client.go
WIP dependent on merge of #207
=> Additional endpoint related changes

logging_windows.go, mig-agent/agentcontext/env_windows.go
Hello,
here is my first pull request for mig ;-)
It contains some simple fixes to allow building a windows client with the new agentcontext feature and fix the old bug in logging_windows.
Building module memory still fail.
=> [minor/bug] fix to build windows agent

modules/netstat/netstat_darwin.go, modules/netstat/netstat_linux.go
Corrects an issue with Darwin -ci flag searches, and a bug in Linux IPv6 -ci searches. Also adds support for scanning IPv4 mapped IPv6 addresses.
=> Fixes in netstat module

modules/file/file.go
Here the right Monday patch  ;-)
Block in line 838 is useful for first path other subdirs path are fixed in 844
=> [medium/bug] windows bug in pathwalk, fixes #213

mig-agent/agentcontext/env_windows.go
use wmic instead of the long and translated systeminfo
=> [medium/bug] fix windows agent environment

client/client.go, modules/file/doc.rst, modules/file/file.go, modules/file/file_test.go, modules/file/paramscreator.go
These patches implement the limit of walking errors returned by the file module and address a few other minor things.
r? @ameihm0912
=> File limits

modules/pkg/doc.rst, modules/pkg/paramscreator.go, modules/pkg/pkg.go
=> [minor] support filtering by version in pkg module

Makefile, client/client.go, doc/agent.rst, doc/api.rst, doc/concepts.rst, doc/configuration.rst, doc/loader.rst, mig-api/manifest_endpoints.go
First updates to loader documentation...
More to come...
=> Some loader documentation updates

client/client.go, client/mig-console/investigator.go, database/investigators.go, database/schema.sql, doc/agent.rst, doc/api.rst, doc/configuration.rst, doc/loader.rst, loader.go, mig-api/investigator_endpoints.go
This fixes up some additional comments that were in #231
=> Additional documentation for loader functionality

mig-api/action_endpoints.go, mig-api/api.go, mig-api/command_endpoints.go, mig-api/investigator_endpoints.go
This may or may not be a good idea.
=> [minor] reorganize api endpoints to satisfy my OCD-ness

tools/standalone_install.sh
Signed-off-by: Brandon Myers <bmyers@mozilla.com>
=> Fix wording in prompt in standalone install script

client/mig-console/search.go, database/loader.go, investigator.go, mig-api/api.go
Minor fixes related to recent permissions changes
=> Fixes related to permissions

manifest.go, mig-loader/loader.go, mig-loader/loader_test.go
Adds tests for loader signature validation; this also resolves an issue related to duplicate signatures in the manifest.
=> Add tests for loader signature validation

action.go, client/mig/main.go
Adds functionality to mig-cmd in addition to various bug fixes to
correctly support multiple signature verification with ACL module
weights.
This implementation is rudimentary in the sense it gives an investigator
the ability to output a signed action, which can be handed off to
another investigation for application of a second signature and
execution in the system.
=> [medium] enhance support for multiple action signatures

vendor/github.com/jvehent/service-go/service_linux.go
revendor service-go to resolve issue with systemd starting agent before network is available
=> [minor] revendor service-go

.gitignore, tools/vagrant/Vagrantfile, tools/vagrant/bootstrap.sh
Basic vagrant setup to create an ubuntu virtualbox, install go, setup GOPATH and link host's project directory into the GOPATH.  I'm using a mac as the host.
=> [minor] add vagrant dev box

Makefile
We want to make sure signatures are applied to the compiled binaries in
addition to the loader package.
Resolves #278
=> [minor] additional signing for osx to be compatible with sierra

README.md
A small edit in **`README.md`**. :pencil:
*Yours,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:
=> [doc] Removed gap in README.md

.travis.yml, Makefile, client/mig-console/available_modules.go, client/mig/available_modules.go, mig-agent/available_modules.go, mig-agent/configuration.go, mig-loader/configuration.go
Removes use of symbolic links for configuration files which cause issues when building on Windows. This also adds some tests to Travis to make sure our default built-in configuration matches what we have as examples in the conf directory.
=> Remove symlinks from repo

agent.go, mig-agent/agent.go, mig-agent/context.go
Adds functionality as per issue #229
=> [Minor] List of agent's enabled modules added to heartbeat according to issue #229

Makefile
=> [minor] build prior to install in makefile install targets

pgp/pinentry/pinentry.go
See #316 for additional details
=> [minor] update pgp getPINNaïve so stty -echo is successful

.travis.yml, Dockerfile, tools/standalone_install.sh
Bunch of minor tweaks to Dockerfile and the standalone installation.
=> Updates for Docker build and standalone installation

mig-agent/agent.go
@ameihm0912 please take a look.
=> [minor] Add an option to print agent settings, fixes #280

mig-agent/agent.go, mig-agent/config.go, mig-agent/daemonize_windows.go, service/service_windows.go
Update service package to correctly daemonize the agent on Windows, tested on Windows 10.
Resolves #320
=> Resolve issues installing the agent as a service on Windows

Makefile, manifest.go, mig-agent/daemonize_darwin.go, mig-agent/daemonize_linux.go, mig-agent/daemonize_windows.go, mig-loader/agentops.go, mig-loader/context.go, mig-loader/loader.go, mig-loader/svc_darwin.go, mig-loader/svc_linux.go, mig-loader/svc_windows.go, tools/win-loader-wxs/license.rtf, tools/win-loader-wxs/mig-loader.wxs, tools/win-loader-wxs/userreg.wxs
Adds support for Windows to mig-loader.
An example WiX configuration for loader MSI builds is also added.
The MSI installs mig-loader in a service mode, where it executes periodically to keep the agent on the platform up to date.
=> [major] Windows support in mig-loader

action.go
=> [minor/bug] in SignAction, remove temporary file

client/mig-console/manifest.go
displays manifest objects in command line sha256sum style format
=> [minor] add shasum command in manifest reader

mig-agent/agent.go
=> [easy/up-for-grabs] Add additional line for unknown investigator

modules/file/file.go, modules/file/file_test.go, modules/file/paramscreator.go
Makes a few minor changes to the file module for consistency.
A test has also been added to validate symbolic link following for regular files.
The file units have been modified with a few helper functions, and small consistency fixes.
=> file module cleanup, add symlink test, rework file tests

modules/file/file.go
In cases where multiple paths are present in a single search (e.g.,
-path is used more than once with the mig command line) the maxdepth
option was not behaving correctly.
pathWalk would examine the paths in scope for a search to determine if
it should be considered. Upon finding one, it would not break out of the
loop, so depending on the ordering, the search may not be marked as
current even if it was under the root of a search path.
This was resulting in the current directory depth not being consistently
reduced upon returning from pathWalk, causing the current depth to
continuously increase for a given search.
=> file: fix bug in maxdepth handling with multiple paths in a search

client/mig-console/action_launcher.go
=> mig-console: error on listagents with no target in action launcher

doc/configuration.rst
=> update config guides build prep section

client/client.go, client/mig-action-generator/generator.go, client/mig-action-verifier/verifier.go, client/mig-agent-search/main.go, client/mig-console/action_launcher.go, client/mig-console/console.go, client/mig/main.go, mig-runner/context.go
This PR contains a bunch of code and user interface related improvements to the client tools, including better handling of errors and consistency in output formatting.
=> Improvements to client tools

README.md
http://list.mig.ninja/listinfo/list
Service Unavailable
=> Delete deprecated mailing list from README
